namespace odl3d;

/// <summary>
/// Specifies the type of shader, either a vertex shader or a fragment shader. The ShaderType enumeration is used to indicate the type of shader being compiled and linked into a shader program, allowing the rendering engine to handle different types of shaders appropriately during the rendering process.
/// </summary>
public enum ShaderType
{
    /// <summary>
    /// Represents a vertex shader, which processes vertex data and is responsible for transforming vertex positions, calculating lighting, and passing data to the fragment shader. Vertex shaders are executed for each vertex in a mesh and are a fundamental part of the rendering pipeline.
    /// </summary>
    Vertex,
    
    /// <summary>
    /// Represents a fragment shader, which processes pixel data and is responsible for determining the final color of each pixel on the screen. Fragment shaders are executed for each fragment generated by rasterization and can perform operations such as texturing, lighting, and color blending to produce the final image.
    /// </summary>
    Fragment
}