<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Platform>x64</Platform>
        <Platforms>x64</Platforms>
        <Configurations>Debug;Release</Configurations>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Nullable>disable</Nullable>
        <Authors>Marijn Herrebout</Authors>
        <Copyright>Marijn Herrebout</Copyright>
        <RepositoryUrl>https://github.com/Marin-MK/odl3d</RepositoryUrl>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Debug'">
        <Optimize>False</Optimize>
        <OutputPath>build/Debug</OutputPath>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Release'">
        <Optimize>True</Optimize>
        <OutputPath>build/Release</OutputPath>
    </PropertyGroup>

    <ItemGroup>
        <Compile Remove="demo/**/*.cs;tests/**/*.cs;external/**/*.cs" />
        <ProjectReference Include="external/decodl/decodl.csproj" />
    </ItemGroup>

    <ItemGroup>
        <!-- GLFW -->
        <None Include="bin/glfw3.dll" Condition="Exists('bin/glfw3.dll')">
            <Link>bin/glfw3.dll</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="bin/libglfw.3.dylib" Condition="Exists('bin/libglfw.3.dylib')">
            <Link>bin/libglfw.3.dylib</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="bin/libglfw.3.so" Condition="Exists('bin/libglfw.3.so')">
            <Link>bin/libglfw.3.so</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>

        <!-- Freetype -->
        <None Include="bin/freetype.dll" Condition="Exists('bin/freetype.dll')">
            <Link>bin/freetype.dll</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="bin/libfreetype.6.dylib" Condition="Exists('bin/libfreetype.6.dylib')">
            <Link>bin/libfreetype.6.dylib</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Include="bin/libfreetype.6.so" Condition="Exists('bin/libfreetype.6.so')">
            <Link>bin/libfreetype.6.so</Link>
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
