<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyName>odl3d.Tests.Native</AssemblyName>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
        <PackageReference Include="xunit" Version="2.9.2" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\odl3d.csproj">
            <Private>true</Private>
        </ProjectReference>
    </ItemGroup>

    <Target Name="CopyOdl3dAssemblyToNativeTestOutput" AfterTargets="Build">
        <Copy
            SourceFiles="$(MSBuildProjectDirectory)/../../build/$(Configuration)/$(TargetFramework)/odl3d.dll"
            DestinationFolder="$(OutDir)"
            SkipUnchangedFiles="true" />
    </Target>

</Project>